spring.application.name=ms-gestion-academica
server.port=${PORT:8081}

#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/ms_gestion_academica_db}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aulabo_db?currentSchema=gestion_academica}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aulabo_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aulabo_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false